### ISSUE TITLE
Overflowing content

### ISSUE THREAD

**Issue by Aanandgupta** [ayush5588/ProjectStats#2]
Due to some links content is overflowed and we have to scroll page expected behaviour would be to display it in next line
![Screenshot (149)](https://user-images.githubusercontent.com/71023799/108604010-523caf80-73d1-11eb-984c-9518342f7ace.png)
![Screenshot (150)](https://user-images.githubusercontent.com/71023799/108604017-58329080-73d1-11eb-9864-79b7b9a7b5e8.png)

**Comment by ayush5588** [comment]
Thanks @Aanandgupta for bringing it up. I actually never made it keeping the resizing factor in mind. Would you like to take up this issue?

**Comment by ayush5588** [comment]
I am thinking that instead of giving that big repo url we can make use of URL Shortener. What do you think?

**Comment by Aanandgupta** [comment]
> I am thinking that instead of giving that big repo url we can make use of URL Shortener. What do you think?

URL shortener i have not heard of that whats that?

**Comment by ayush5588** [comment]
@Aanandgupta Sorry for late reply. Was busy with some stuff. URL shortener basically does what it says. It just take a long URL and trim it down to a small URL.
